### ISSUE TITLE
[vireo] IndexError: too many indices for array

### ISSUE THREAD

**Issue by luzgaral** [single-cell-genetics/vireo#11]
Hi,

I'm getting this error running Vireo:

```
[vireo] Loading cell VCF file ...
[vireo] Demultiplex 7254 cells to 1 donors with 72306 variants.
[vireo] lower bound ranges [-3518489.0, -3518489.0, -3518489.0]
[vireo] allelic rate mean and concentrations:
[[0.337 0.485 0.597]]
[[ 928999.7 2988437.  1366544.3]]
[vireo] donor size before removing doublets:
donor0
7254
Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/myenvSC/bin/vireo", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/my-conda-envs/myenvSC/lib/python3.7/site-packages/vireoSNP/vireo.py", line 204, in main
    ASE_mode=options.ASE_mode)
  File "/home/jovyan/my-conda-envs/myenvSC/lib/python3.7/site-packages/vireoSNP/utils/vireo_wrap.py", line 122, in vireo_wrap
    doublet_prob, ID_prob = modelCA.predict_doublet(AD, DP)
  File "/home/jovyan/my-conda-envs/myenvSC/lib/python3.7/site-packages/vireoSNP/utils/vireo_model.py", line 313, in predict_doublet
    GT_both = add_doublet_GT(self.GT_prob)
  File "/home/jovyan/my-conda-envs/myenvSC/lib/python3.7/site-packages/vireoSNP/utils/vireo_model.py", line 394, in add_doublet_GT
    s_idx1 = sp_idx[:, 0]
IndexError: too many indices for array
```

I have several multiplexed samples but one (and I don't know the donor but need to link it to the rest of samples), that's why I'm running Vireo with `N_DONOR=1` in this sample. Not sure if the error is related to this, but it looks like it is due to querying a long array.

Also, we had to use `--noPlot` in some samples as the processes were killed by a lack of memory (RAM: 50GB, CPUs: 16).

Any help would be really appreciated!

Many thanks in advance.

**Comment by huangyh09** [comment]
Hi,

I think `N_DONOR=1` is probably the reason. This parameter means the number of donors that are mixed in pool, which should be more than one in your data and you should put `n_donor_with_know_GT + 1`.

I didn't expect `plotting` will cause such memory requirement, but I'll look into it.

Thanks,
Yuanhua
