### ISSUE TITLE
IndexError: index (875606) out of range

### ISSUE THREAD

**Issue by maxozo** [single-cell-genetics/vireo#74]
Any idea on whats causing this error and how to fix it?
I run it like this -
`vireo -c cellsnp_CRD_CMB13016570 -N 10 -o vireo_CRD_CMB13016570  -d Study_Merge_sorted_Expected_CRD_CMB13016570.vcf.gz --forceLearnGT -t GT --randSeed 6 -p 12 --nInit 200`
For most of samples its ok, but for the particular one I get:

```
[vireo] Loading cell folder ...
[vireo] Loading donor VCF file ...
[vireo] 29292 out 876838 variants matched to donor VCF
Traceback (most recent call last):
  File "/opt/conda/bin/vireo", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/vireoSNP/vireo.py", line 160, in main
    cell_dat, donor_vcf = match_donor_VCF(cell_dat, donor_vcf)
  File "/opt/conda/lib/python3.9/site-packages/vireoSNP/utils/io_utils.py", line 34, in match_donor_VCF
    cell_dat['AD'] = cell_dat['AD'][idx1, :]
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_index.py", line 138, in _validate_indices
    row = self._asindices(row, M)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_index.py", line 170, in _asindices
    raise IndexError('index (%d) out of range' % max_indx)
IndexError: index (875606) out of range
```

**Comment by maxozo** [comment]
Looking more into this it seems that the error wight happens because the cell_dat['variants'] has more variants than donor_vcf['variants'] and the way the matching is done in vireo (https://github.com/single-cell-genetics/vireo/blob/8bd1f0bf703396c40b1656edad127c327715358a/vireoSNP/utils/vireo_base.py#L169-L180) produces indexes that exceed what variant position and hence fails when we try to extract the cell_dat['AD'] in https://github.com/single-cell-genetics/vireo/blob/8bd1f0bf703396c40b1656edad127c327715358a/vireoSNP/utils/io_utils.py#L34

Not sure if i am right, but perhaps this helps?

**Comment by maxozo** [comment]
ok, just if anyone else encourages this issue: nothing to really do with Vireo, CellSNP for some reason produced a vcf that has much more variants () then annotations in AD DP files (876838 vs 87891). Hence Vireo failed in merging subsetting the dataframe based on a larger index than available.  <img width="367" alt="Screenshot 2022-11-03 at 09 19 48" src="https://user-images.githubusercontent.com/22347136/199684978-ad2dbab7-ef25-48cc-802e-f1bb81662ac7.png">
Will close this issue now.
